/camera_node:
  ros__parameters:
    camera_info_url: package://rm_vision_bringup/config/camera_info.yaml
    exposure_time: 2500 # 曝光时间，单位为微秒（us）
    gain: 8.0   #增益值，用于调整图像亮度

/serial_driver:
  ros__parameters:
    timestamp_offset: 0.006 #时间戳偏移量，单位为秒
    device_name: /dev/ttyACM0
    baud_rate: 460800
    flow_control: none #流控制方式，这里设置为无流控制
    parity: none #校验位设置，这里设置为无校验
    stop_bits: "1" #停止位数量，这里设置为1个停止位

/armor_detector:
  ros__parameters:
    debug: true

    detect_color: 0
    binary_thres: 85

    light.min_ratio: 0.1 #最小光强比例，用于过滤噪声
    armor.min_light_ratio: 0.8 #最小装甲板光强比例，用于过滤噪声

    classifier_threshold: 0.1 #分类器阈值，用于判断检测结果的置信度
    ignore_classes: ["negative"] #忽略的类别列表，这里设置为忽略“negative”类别

/armor_tracker:
  ros__parameters:
    target_frame: odom #目标帧，这里是odom，表示里程计坐标系
    max_armor_distance: 10.0 #最大装甲板距离，单位为米

    ekf: #扩展卡尔曼滤波器的参数
      sigma2_q_xyz: 0.05  #位置噪声方差
      sigma2_q_yaw: 5.0  #偏航角噪声方差
      sigma2_q_r: 80.0  #旋转噪声方差

      r_xyz_factor: 4e-5  #位置测量噪声因子
      r_yaw: 5e-3  #偏航角测量噪声因子

    tracker:
      max_match_distance: 0.5  #最大匹配距离，单位为米
      max_match_yaw_diff: 1.0  #最大匹配偏航角差异，单位为弧度

      k: 0.092
      bias_time: 0  #偏差时间
      s_bias: 0.19133  #速度偏差
      z_bias: 0.21265  #高度偏差

      tracking_thres: 5  #跟踪阈值
      lost_time_thres: 1.0   #丢失时间阈值，单位为秒
